version: "2"
services:
  gamifydb:
    container_name: gamifydb
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db/gamifydb:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_DATABASE=gamifydb

  wavesdb:
    container_name: wavesdb
    image: mariadb
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./db/wavesdb:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_DATABASE=wavesdb
      

  redis:
    image: redis
    expose:
      - 6379
  gamify-backend:
    container_name: gamify-backend
    build: gamify
    command: npm run dev
    restart: always
    volumes:
      - .:/usr/app/gamify-backend
      - /usr/app/gamify-backend/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - gamifydb
      - redis

  waves-backend:
    container_name: waves-backend
    build: waves-backend
    command: npm run dev
    volumes:
      - .:/usr/app/waves-backend
      - /usr/app/waves-backend/node_modules
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_DATABASE=wavesdb
      - NODE_ENV=dev
      - PORT=5000
      - OAUTH_BASE_URI=https://stage.vivaconagua.org
      - CLIENT_ID=wavesdev
      - CLIENT_SECRET=wavesdev
      - REDIRECT_URI=http://localhost/waves/api/v1/oauth
    ports:
      - "5000:5000"
    depends_on:
      - wavesdb
      - redis
    
